### ISSUE TITLE
Restrict access to 'admin' modules

### ISSUE THREAD

**Issue by phillipadsmith** [concierge/Kassy#138]
As promised, @mrkno, opening up an issue to discuss how you'd imagine approaching the restriction of access to certain core modules/commands that are administrative in nature, e.g.:

- `/disable`
- `/kpm`
- `/restart`
- `/shutdown`
- `/update`

If you have thoughts on how to approach this, that would be great to hear. :-)

**Comment by mrkno** [comment]
The origional intention with this was to have an admin section within the root `config.json`. That section might look like the following:

```json
{
	"admin": {
		"users": [
			{
				"username": <username>,
				"threads": [<threadId>],
				"permissions": [<permissionLevel>]
			}
		]
	}
}
```

**Comment by phillipadsmith** [comment]
@mrkno Did this actually get merged into the recent 4.0alpha PR? I ask because both the `admin` command and the functionality from adding an admin section to the config.json don't appear to be working in 4.0alpha?

**Comment by ParasDPain** [comment]
@phillipadsmith I believe a few core modules have been removed in this [commit](https://github.com/concierge/Kassy/pull/175/commits/6524413f7430f461f222397e319b49dfe47114a9) from the main build and into their own separate repos, because they were not as readily used.

You should be able to add the [admin](https://github.com/concierge/admin) module manually though

Other removed modules can be found in [Concierge's](https://github.com/concierge) repo list as well.

**Comment by ParasDPain** [comment]
@mrkno Now that `core` modules can be added/removed by the user manually; does this procedure has to be manual or can be automated through a package manager? 

How about we remove all `core` modules and let the user choose which ones to install during **Kassy** installation? A simple script should do the job or can be later added into the GUI installer plans #180 Otherwise most new users will never be aware of of all available `core` modules, although the same problem persists for normal `modules` as well.
A user has to manually check via the **Wiki** for any newly added/updated modules, or they remain in the dark.

**Comment by mrkno** [comment]
Due to it breaking the ability to nicely update, there is no nice way for a package manager to deal with removing any file that is committed to the repo. The current options are the following:
- We remove all the remaining core modules. This removes the ability to shutdown/update. It also means that `kpm` won't be installed so it is comparatively painful to install things. I removed some of the modules that were there before to reduce the effect of pre-installed module problems.
- We leave things as they are. This depends on people installing something like admin if they want to disable a core module.
- We allow pre-installed modules to be uninstalled. It will break updates and present a whole range of potential problems (what if `kpm` is uninstalled, how do we reinstall given they are in a different format). 
- We have a script to do some kind of post install on first startup. This is an extra layer of complication and maintenance that needs to be performed. We also can't access the global config until after the platform is initialized which complicates things on this front.
